/*
 * generated by Xtext 2.19.0
 */
package mixin.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MixinGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mixin.Mixin.Model");
		private final Assignment cInstructionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cInstructionsInstructionParserRuleCall_0 = (RuleCall)cInstructionsAssignment.eContents().get(0);
		
		//Model:
		//	instructions+=Instruction*;
		@Override public ParserRule getRule() { return rule; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment() { return cInstructionsAssignment; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_0() { return cInstructionsInstructionParserRuleCall_0; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mixin.Mixin.Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMoveParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCleanParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Instruction:
		//	Move | Clean;
		@Override public ParserRule getRule() { return rule; }
		
		//Move | Clean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Move
		public RuleCall getMoveParserRuleCall_0() { return cMoveParserRuleCall_0; }
		
		//Clean
		public RuleCall getCleanParserRuleCall_1() { return cCleanParserRuleCall_1; }
	}
	public class MoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mixin.Mixin.Move");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cQuantityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cQuantityINTTerminalRuleCall_1_0 = (RuleCall)cQuantityAssignment_1.eContents().get(0);
		private final Keyword cMLKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFromKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cCupKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSourceCupAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSourceCupINTTerminalRuleCall_5_0 = (RuleCall)cSourceCupAssignment_5.eContents().get(0);
		private final Keyword cToKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cCupKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDestinationCupAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDestinationCupINTTerminalRuleCall_8_0 = (RuleCall)cDestinationCupAssignment_8.eContents().get(0);
		
		//Move:
		//	"move" quantity=INT "mL" "from" "cup" sourceCup=INT "to" "cup" destinationCup=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//"move" quantity=INT "mL" "from" "cup" sourceCup=INT "to" "cup" destinationCup=INT
		public Group getGroup() { return cGroup; }
		
		//"move"
		public Keyword getMoveKeyword_0() { return cMoveKeyword_0; }
		
		//quantity=INT
		public Assignment getQuantityAssignment_1() { return cQuantityAssignment_1; }
		
		//INT
		public RuleCall getQuantityINTTerminalRuleCall_1_0() { return cQuantityINTTerminalRuleCall_1_0; }
		
		//"mL"
		public Keyword getMLKeyword_2() { return cMLKeyword_2; }
		
		//"from"
		public Keyword getFromKeyword_3() { return cFromKeyword_3; }
		
		//"cup"
		public Keyword getCupKeyword_4() { return cCupKeyword_4; }
		
		//sourceCup=INT
		public Assignment getSourceCupAssignment_5() { return cSourceCupAssignment_5; }
		
		//INT
		public RuleCall getSourceCupINTTerminalRuleCall_5_0() { return cSourceCupINTTerminalRuleCall_5_0; }
		
		//"to"
		public Keyword getToKeyword_6() { return cToKeyword_6; }
		
		//"cup"
		public Keyword getCupKeyword_7() { return cCupKeyword_7; }
		
		//destinationCup=INT
		public Assignment getDestinationCupAssignment_8() { return cDestinationCupAssignment_8; }
		
		//INT
		public RuleCall getDestinationCupINTTerminalRuleCall_8_0() { return cDestinationCupINTTerminalRuleCall_8_0; }
	}
	public class CleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mixin.Mixin.Clean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCleanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCleanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Clean:
		//	{Clean} "clean";
		@Override public ParserRule getRule() { return rule; }
		
		//{Clean} "clean"
		public Group getGroup() { return cGroup; }
		
		//{Clean}
		public Action getCleanAction_0() { return cCleanAction_0; }
		
		//"clean"
		public Keyword getCleanKeyword_1() { return cCleanKeyword_1; }
	}
	
	
	private final ModelElements pModel;
	private final InstructionElements pInstruction;
	private final MoveElements pMove;
	private final CleanElements pClean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MixinGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pInstruction = new InstructionElements();
		this.pMove = new MoveElements();
		this.pClean = new CleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mixin.Mixin".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	instructions+=Instruction*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Instruction:
	//	Move | Clean;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//Move:
	//	"move" quantity=INT "mL" "from" "cup" sourceCup=INT "to" "cup" destinationCup=INT;
	public MoveElements getMoveAccess() {
		return pMove;
	}
	
	public ParserRule getMoveRule() {
		return getMoveAccess().getRule();
	}
	
	//Clean:
	//	{Clean} "clean";
	public CleanElements getCleanAccess() {
		return pClean;
	}
	
	public ParserRule getCleanRule() {
		return getCleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
