/*
 * generated by Xtext 2.19.0
 */
package xtextExample.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xtextExample.ui.internal.XtextExampleActivator;

public class XtextExampleUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextExampleActivator.getInstance().getInjector("xtextExample.XtextExample");
	}

}
