/*
 * generated by Xtext 2.19.0
 */
package mixin


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MixinStandaloneSetup extends MixinStandaloneSetupGenerated {

	def static void doSetup() {
		new MixinStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
