/*
 * generated by Xtext 2.19.0
 */
package mixin


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MixinRuntimeModule extends AbstractMixinRuntimeModule {
}
