/*
 * generated by Xtext 2.19.0
 */
package xtextExample.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import xtextExample.ui.internal.XtextExampleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XtextExampleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XtextExampleActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XtextExampleActivator activator = XtextExampleActivator.getInstance();
		return activator != null ? activator.getInjector(XtextExampleActivator.XTEXTEXAMPLE_XTEXTEXAMPLE) : null;
	}

}
