/**
 * generated by Xtext 2.19.0
 */
package xtextExample.xtextExample.impl;

import org.eclipse.emf.ecore.EClass;

import xtextExample.xtextExample.DataType;
import xtextExample.xtextExample.XtextExamplePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataTypeImpl extends TypeImpl implements DataType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XtextExamplePackage.Literals.DATA_TYPE;
  }

} //DataTypeImpl
