DROP TRIGGER CATEGORIE_ABONNE;

DROP TABLE CARACTERISE;
DROP TABLE EMPRUNT;
DROP TABLE EXEMPLAIRE;
DROP TABLE ABONNE;
DROP TABLE ECRIT;
DROP TABLE LIVRE;
DROP TABLE MOT_CLE;
DROP TABLE AUTEUR;


/* Création tables */
CREATE TABLE AUTEUR (
       ID NUMERIC(4,0),
       CONSTRAINT PK_AUTEUR PRIMARY KEY(ID),
       NOM VARCHAR(20),
       PRENOM VARCHAR(20),
       NATIONALITE VARCHAR(20)
);

CREATE TABLE MOT_CLE (
	MOT VARCHAR(20),
	CONSTRAINT PK_MOT_CLE PRIMARY KEY(MOT),
	PERE VARCHAR(20),
	CONSTRAINT FK_MOT_CLE FOREIGN KEY(PERE) REFERENCES MOT_CLE(MOT)
);

CREATE TABLE LIVRE (
	ISBN VARCHAR(20),
	CONSTRAINT PK_LIVRE PRIMARY KEY(ISBN),
	TITRE VARCHAR(50) CONSTRAINT LI_TITRE NOT NULL, 
	SIECLE NUMERIC(2,0) CHECK (SIECLE BETWEEN 0 and 21),
	CATEGORIE VARCHAR(20),
	CONSTRAINT FK_LIVRE_CAT FOREIGN KEY(CATEGORIE) REFERENCES MOT_CLE(MOT)
);

CREATE TABLE ECRIT (
       ID_AUTEUR NUMERIC(4,0),
       CONSTRAINT FK_ECRIT_ID FOREIGN KEY(ID_AUTEUR) REFERENCES AUTEUR(ID),
       ISBN VARCHAR(20),
       CONSTRAINT FK_ECRIT_ISBN FOREIGN KEY(ISBN) REFERENCES LIVRE(ISBN),
       CONSTRAINT PK_ECRIT PRIMARY KEY(ID_AUTEUR,ISBN)
);

CREATE TABLE ABONNE (
	NUM_AB  NUMERIC(6,0),
	CONSTRAINT PK_ABONNE PRIMARY KEY(NUM_AB),
	NOM VARCHAR(30) CONSTRAINT AB_NOM NOT NULL, 
	PRENOM VARCHAR(20), 
	VILLE VARCHAR(30),
	DATE_NAI DATE,
	CAT_AB VARCHAR(10),
	CONSTRAINT DOM_CAT_AB CHECK (CAT_AB IN ('REGULIER','OCCASIONNEL','A PROBLEME','EXCLU')),
	TYPE_CAT VARCHAR(10),
	CONSTRAINT DOM_TYPE_CAT CHECK (TYPE_CAT IN ('ADULTE','ENFANT')),
 	TARIF NUMERIC(5,0),
 	REDUC NUMERIC(3,0)
);

CREATE TABLE EXEMPLAIRE (
	NUMERO NUMERIC(4,0),
	CONSTRAINT PK_EXEMPLAIRE PRIMARY KEY(NUMERO),
	DATE_ACHAT DATE, 
	PRIX NUMERIC(5,2), 
	CODE_PRET VARCHAR(20),
	CONSTRAINT DOM_CODE_PRET CHECK (CODE_PRET IN ('EXCLU','EMPRUNTABLE','CONSULTABLE')),
	ETAT VARCHAR(15),
	CONSTRAINT DOM_ETAT CHECK (ETAT IN ('BON','ABIME','EN_REPARATION')), 
	ISBN VARCHAR(20),
	CONSTRAINT FK_EXEMPLAIRE FOREIGN KEY(ISBN) REFERENCES LIVRE(ISBN)
);

CREATE TABLE EMPRUNT (
	NUM_AB  NUMERIC(6,0),
	CONSTRAINT FK_EMPRUNT_AB FOREIGN KEY(NUM_AB) REFERENCES ABONNE(NUM_AB),
	NUM_EX NUMERIC (4,0),
	CONSTRAINT FK_EMPRUNT_EX FOREIGN KEY(NUM_EX) REFERENCES EXEMPLAIRE(NUMERO),
	CONSTRAINT PK_EMPRUNT PRIMARY KEY(NUM_AB,NUM_EX),
	D_EMPRUNT DATE, 
	D_RETOUR DATE, 
	D_RET_REEL DATE, 
	NB_RELANCE NUMERIC(1,0),
	CONSTRAINT DOM_NB_RELANCE CHECK (NB_RELANCE IN (1,2,3))
);

CREATE TABLE CARACTERISE (
	ISBN VARCHAR(20),
	CONSTRAINT FK_CARAC_ISBN FOREIGN KEY(ISBN) REFERENCES LIVRE(ISBN),
	MOT VARCHAR(20),
	CONSTRAINT FK_CARAC_MOT FOREIGN KEY(MOT) REFERENCES MOT_CLE(MOT),
	CONSTRAINT PK_CARAC PRIMARY KEY(ISBN,MOT)
);


/* Création triggers */
CREATE TRIGGER CATEGORIE_ABONNE AFTER INSERT OR UPDATE ON ABONNE
BEGIN
	IF DATEDIFF(CURRENT_DATE,DATE_NAI)>16
	   THEN NEW.TYPE_CAT='ADULTE';
	END IF;
	
	IF DATEDIFF(CURRENT_DATE,DATE_NAI)<=16
	   THEN NEW.TYPE_CAT='ENFANT';
	END IF;

	IF DATE_NAI==NULL
	   THEN NEW.TYPE_CAT=NULL;
	END IF;
END;
