/*
 * generated by Xtext 2.19.0
 */
package xtextExample.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXtextExampleScopeProvider extends DelegatingScopeProvider {
}
