/*
 * generated by Xtext 2.19.0
 */
package mixin.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import mixin.ide.contentassist.antlr.internal.InternalMixinParser;
import mixin.services.MixinGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MixinParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MixinGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MixinGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getMoveAccess().getGroup(), "rule__Move__Group__0");
			builder.put(grammarAccess.getCleanAccess().getGroup(), "rule__Clean__Group__0");
			builder.put(grammarAccess.getModelAccess().getInstructionsAssignment(), "rule__Model__InstructionsAssignment");
			builder.put(grammarAccess.getMoveAccess().getQuantityAssignment_1(), "rule__Move__QuantityAssignment_1");
			builder.put(grammarAccess.getMoveAccess().getSourceCupAssignment_5(), "rule__Move__SourceCupAssignment_5");
			builder.put(grammarAccess.getMoveAccess().getDestinationCupAssignment_8(), "rule__Move__DestinationCupAssignment_8");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MixinGrammarAccess grammarAccess;

	@Override
	protected InternalMixinParser createParser() {
		InternalMixinParser result = new InternalMixinParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MixinGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MixinGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
