/**
 * generated by Xtext 2.19.0
 */
package mixin.ui.contentassist;

import mixin.ui.contentassist.AbstractMixinProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MixinProposalProvider extends AbstractMixinProposalProvider {
}
