/**
 * generated by Xtext 2.19.0
 */
package mixin;

import mixin.MixinStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MixinStandaloneSetup extends MixinStandaloneSetupGenerated {
  public static void doSetup() {
    new MixinStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
