/**
 * generated by Xtext 2.19.0
 */
package xtextExample.xtextExample;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xtextExample.xtextExample.XtextExamplePackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
