/*
 * generated by Xtext 2.19.0
 */
package xtextExample


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XtextExampleStandaloneSetup extends XtextExampleStandaloneSetupGenerated {

	def static void doSetup() {
		new XtextExampleStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
