COMPIL = gcc
FLAGS = -lpthread
SOURCES = Q1 Q2 Q3 Q4

all: clean $(SOURCES)

Q1:
	$(COMPIL) $@.c calculC.o -o $@.out $(FLAGS)

Q2:
	$(COMPIL) $@.c calculC.o -o $@.out $(FLAGS)

Q3:
	$(COMPIL) $@.c calculC.o -o $@.out $(FLAGS)

Q4:
	$(COMPIL) $@.c calculC.o -o $@.out $(FLAGS)

clean:
	rm -f *.out