/*
 * generated by Xtext 2.19.0
 */
package mixin.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMixinScopeProvider extends DelegatingScopeProvider {
}
