/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin.impl;

import mixin.mixin.MixinPackage;
import mixin.mixin.Take;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Take</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mixin.mixin.impl.TakeImpl#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link mixin.mixin.impl.TakeImpl#getInputCup <em>Input Cup</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TakeImpl extends InstructionImpl implements Take
{
  /**
   * The default value of the '{@link #getQuantity() <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuantity()
   * @generated
   * @ordered
   */
  protected static final int QUANTITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getQuantity() <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuantity()
   * @generated
   * @ordered
   */
  protected int quantity = QUANTITY_EDEFAULT;

  /**
   * The default value of the '{@link #getInputCup() <em>Input Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputCup()
   * @generated
   * @ordered
   */
  protected static final int INPUT_CUP_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getInputCup() <em>Input Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputCup()
   * @generated
   * @ordered
   */
  protected int inputCup = INPUT_CUP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TakeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MixinPackage.Literals.TAKE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getQuantity()
  {
    return quantity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQuantity(int newQuantity)
  {
    int oldQuantity = quantity;
    quantity = newQuantity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MixinPackage.TAKE__QUANTITY, oldQuantity, quantity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getInputCup()
  {
    return inputCup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInputCup(int newInputCup)
  {
    int oldInputCup = inputCup;
    inputCup = newInputCup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MixinPackage.TAKE__INPUT_CUP, oldInputCup, inputCup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MixinPackage.TAKE__QUANTITY:
        return getQuantity();
      case MixinPackage.TAKE__INPUT_CUP:
        return getInputCup();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MixinPackage.TAKE__QUANTITY:
        setQuantity((Integer)newValue);
        return;
      case MixinPackage.TAKE__INPUT_CUP:
        setInputCup((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MixinPackage.TAKE__QUANTITY:
        setQuantity(QUANTITY_EDEFAULT);
        return;
      case MixinPackage.TAKE__INPUT_CUP:
        setInputCup(INPUT_CUP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MixinPackage.TAKE__QUANTITY:
        return quantity != QUANTITY_EDEFAULT;
      case MixinPackage.TAKE__INPUT_CUP:
        return inputCup != INPUT_CUP_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (quantity: ");
    result.append(quantity);
    result.append(", inputCup: ");
    result.append(inputCup);
    result.append(')');
    return result.toString();
  }

} //TakeImpl
