/**
 * generated by Xtext 2.19.0
 */
package mixin.ide;

import mixin.ide.AbstractMixinIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MixinIdeModule extends AbstractMixinIdeModule {
}
