/**
 * generated by Xtext 2.19.0
 */
package mixin.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mixin.MixinRuntimeModule;
import mixin.MixinStandaloneSetup;
import mixin.ide.MixinIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MixinIdeSetup extends MixinStandaloneSetup {
  @Override
  public Injector createInjector() {
    MixinRuntimeModule _mixinRuntimeModule = new MixinRuntimeModule();
    MixinIdeModule _mixinIdeModule = new MixinIdeModule();
    return Guice.createInjector(Modules2.mixin(_mixinRuntimeModule, _mixinIdeModule));
  }
}
