/*
 * generated by Xtext 2.19.0
 */
package xtextExample.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import xtextExample.parser.antlr.internal.InternalXtextExampleParser;
import xtextExample.services.XtextExampleGrammarAccess;

public class XtextExampleParser extends AbstractAntlrParser {

	@Inject
	private XtextExampleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXtextExampleParser createParser(XtextTokenStream stream) {
		return new InternalXtextExampleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}

	public XtextExampleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XtextExampleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
