/**
 * generated by Xtext 2.19.0
 */
package mixin.validation;

import mixin.validation.AbstractMixinValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MixinValidator extends AbstractMixinValidator {
}
