/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clean</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mixin.mixin.MixinPackage#getClean()
 * @model
 * @generated
 */
public interface Clean extends Instruction
{
} // Clean
