/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.mixin.Exit#getCup <em>Cup</em>}</li>
 * </ul>
 *
 * @see mixin.mixin.MixinPackage#getExit()
 * @model
 * @generated
 */
public interface Exit extends Instruction
{
  /**
   * Returns the value of the '<em><b>Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cup</em>' attribute.
   * @see #setCup(int)
   * @see mixin.mixin.MixinPackage#getExit_Cup()
   * @model
   * @generated
   */
  int getCup();

  /**
   * Sets the value of the '{@link mixin.mixin.Exit#getCup <em>Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cup</em>' attribute.
   * @see #getCup()
   * @generated
   */
  void setCup(int value);

} // Exit
