/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mix</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.mixin.Mix#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link mixin.mixin.Mix#getDestinationCup <em>Destination Cup</em>}</li>
 * </ul>
 *
 * @see mixin.mixin.MixinPackage#getMix()
 * @model
 * @generated
 */
public interface Mix extends Instruction
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see mixin.mixin.MixinPackage#getMix_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link mixin.mixin.Mix#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Destination Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination Cup</em>' attribute.
   * @see #setDestinationCup(int)
   * @see mixin.mixin.MixinPackage#getMix_DestinationCup()
   * @model
   * @generated
   */
  int getDestinationCup();

  /**
   * Sets the value of the '{@link mixin.mixin.Mix#getDestinationCup <em>Destination Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination Cup</em>' attribute.
   * @see #getDestinationCup()
   * @generated
   */
  void setDestinationCup(int value);

} // Mix
