/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mixin.mixin.MixinFactory
 * @model kind="package"
 * @generated
 */
public interface MixinPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mixin";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Mixin.mixin";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mixin";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MixinPackage eINSTANCE = mixin.mixin.impl.MixinPackageImpl.init();

  /**
   * The meta object id for the '{@link mixin.mixin.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.mixin.impl.ModelImpl
   * @see mixin.mixin.impl.MixinPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mixin.mixin.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.mixin.impl.InstructionImpl
   * @see mixin.mixin.impl.MixinPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mixin.mixin.impl.MoveImpl <em>Move</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.mixin.impl.MoveImpl
   * @see mixin.mixin.impl.MixinPackageImpl#getMove()
   * @generated
   */
  int MOVE = 2;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__QUANTITY = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__SOURCE_CUP = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Destination Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE__DESTINATION_CUP = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Move</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link mixin.mixin.impl.CleanImpl <em>Clean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mixin.mixin.impl.CleanImpl
   * @see mixin.mixin.impl.MixinPackageImpl#getClean()
   * @generated
   */
  int CLEAN = 3;

  /**
   * The number of structural features of the '<em>Clean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAN_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link mixin.mixin.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see mixin.mixin.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link mixin.mixin.Model#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see mixin.mixin.Model#getInstructions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Instructions();

  /**
   * Returns the meta object for class '{@link mixin.mixin.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see mixin.mixin.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link mixin.mixin.Move <em>Move</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move</em>'.
   * @see mixin.mixin.Move
   * @generated
   */
  EClass getMove();

  /**
   * Returns the meta object for the attribute '{@link mixin.mixin.Move#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see mixin.mixin.Move#getQuantity()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_Quantity();

  /**
   * Returns the meta object for the attribute '{@link mixin.mixin.Move#getSourceCup <em>Source Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source Cup</em>'.
   * @see mixin.mixin.Move#getSourceCup()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_SourceCup();

  /**
   * Returns the meta object for the attribute '{@link mixin.mixin.Move#getDestinationCup <em>Destination Cup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Destination Cup</em>'.
   * @see mixin.mixin.Move#getDestinationCup()
   * @see #getMove()
   * @generated
   */
  EAttribute getMove_DestinationCup();

  /**
   * Returns the meta object for class '{@link mixin.mixin.Clean <em>Clean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clean</em>'.
   * @see mixin.mixin.Clean
   * @generated
   */
  EClass getClean();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MixinFactory getMixinFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mixin.mixin.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.mixin.impl.ModelImpl
     * @see mixin.mixin.impl.MixinPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INSTRUCTIONS = eINSTANCE.getModel_Instructions();

    /**
     * The meta object literal for the '{@link mixin.mixin.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.mixin.impl.InstructionImpl
     * @see mixin.mixin.impl.MixinPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link mixin.mixin.impl.MoveImpl <em>Move</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.mixin.impl.MoveImpl
     * @see mixin.mixin.impl.MixinPackageImpl#getMove()
     * @generated
     */
    EClass MOVE = eINSTANCE.getMove();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__QUANTITY = eINSTANCE.getMove_Quantity();

    /**
     * The meta object literal for the '<em><b>Source Cup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__SOURCE_CUP = eINSTANCE.getMove_SourceCup();

    /**
     * The meta object literal for the '<em><b>Destination Cup</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE__DESTINATION_CUP = eINSTANCE.getMove_DestinationCup();

    /**
     * The meta object literal for the '{@link mixin.mixin.impl.CleanImpl <em>Clean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mixin.mixin.impl.CleanImpl
     * @see mixin.mixin.impl.MixinPackageImpl#getClean()
     * @generated
     */
    EClass CLEAN = eINSTANCE.getClean();

  }

} //MixinPackage
