/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.mixin.Move#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link mixin.mixin.Move#getSourceCup <em>Source Cup</em>}</li>
 *   <li>{@link mixin.mixin.Move#getDestinationCup <em>Destination Cup</em>}</li>
 * </ul>
 *
 * @see mixin.mixin.MixinPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends Instruction
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see mixin.mixin.MixinPackage#getMove_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link mixin.mixin.Move#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Source Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Cup</em>' attribute.
   * @see #setSourceCup(int)
   * @see mixin.mixin.MixinPackage#getMove_SourceCup()
   * @model
   * @generated
   */
  int getSourceCup();

  /**
   * Sets the value of the '{@link mixin.mixin.Move#getSourceCup <em>Source Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Cup</em>' attribute.
   * @see #getSourceCup()
   * @generated
   */
  void setSourceCup(int value);

  /**
   * Returns the value of the '<em><b>Destination Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination Cup</em>' attribute.
   * @see #setDestinationCup(int)
   * @see mixin.mixin.MixinPackage#getMove_DestinationCup()
   * @model
   * @generated
   */
  int getDestinationCup();

  /**
   * Sets the value of the '{@link mixin.mixin.Move#getDestinationCup <em>Destination Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination Cup</em>' attribute.
   * @see #getDestinationCup()
   * @generated
   */
  void setDestinationCup(int value);

} // Move
