/**
 * generated by Xtext 2.19.0
 */
package mixin.mixin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Take</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mixin.mixin.Take#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link mixin.mixin.Take#getInputCup <em>Input Cup</em>}</li>
 * </ul>
 *
 * @see mixin.mixin.MixinPackage#getTake()
 * @model
 * @generated
 */
public interface Take extends Instruction
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see mixin.mixin.MixinPackage#getTake_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link mixin.mixin.Take#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

  /**
   * Returns the value of the '<em><b>Input Cup</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Cup</em>' attribute.
   * @see #setInputCup(int)
   * @see mixin.mixin.MixinPackage#getTake_InputCup()
   * @model
   * @generated
   */
  int getInputCup();

  /**
   * Sets the value of the '{@link mixin.mixin.Take#getInputCup <em>Input Cup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Cup</em>' attribute.
   * @see #getInputCup()
   * @generated
   */
  void setInputCup(int value);

} // Take
