/*
 * generated by Xtext 2.19.0
 */
package mixin.ui.tests;

import com.google.inject.Injector;
import mixin.ui.internal.MixinActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MixinUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MixinActivator.getInstance().getInjector("mixin.Mixin");
	}

}
