/*
 * generated by Xtext 2.19.0
 */
package mixin.parser.antlr;

import com.google.inject.Inject;
import mixin.parser.antlr.internal.InternalMixinParser;
import mixin.services.MixinGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MixinParser extends AbstractAntlrParser {

	@Inject
	private MixinGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMixinParser createParser(XtextTokenStream stream) {
		return new InternalMixinParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MixinGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MixinGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
